name: MIUI Firmware Fastboot Extractor

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'URL file firmware'
        required: true
      output_name:
        description: 'Pilih jenis image'
        type: choice
        required: true
        options:
          - boot.img
          - system.img
          - logo.bin
          - dtbo.img
          - vbmeta.img
          - scatter.txt

jobs:
  extract-firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Update ke versi terbaru

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip zip curl tar tree

    - name: Clean existing files
      run: |
        rm -rf output hasil.tgz *.zip  # Bersihkan file sebelumnya

    - name: Extract version from URL
      id: extract_version
      run: |
        URL="${{ github.event.inputs.download_url }}"
        # Regex yang lebih komprehensif untuk versi
        VERSION=$(echo "$URL" | grep -oP '[A-Za-z]+\d+\.\d+\.\d+')
        
        if [ -z "$VERSION" ]; then
          echo "::error::Gagal ekstrak versi dari URL! Format URL tidak valid."
          echo "Contoh format yang valid: .../V12.0.1.0.QGKMIXM/..."
          exit 1
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT  # Gunakan metode baru

    - name: Download file
      run: |
        if ! curl -L "${{ github.event.inputs.download_url }}" -o hasil.tgz; then
          echo "::error::Gagal mengunduh file dari URL!"
          exit 1
        fi
        
        # Validasi file TGZ
        if ! tar -tzf hasil.tgz >/dev/null 2>&1; then
          echo "::error::File hasil.tgz tidak valid atau korup!"
          exit 1
        fi

    - name: Extract files
      run: |
        mkdir -p output
        tar -xvzf hasil.tgz -C output
        tree output  # Tampilkan struktur folder untuk debugging

    - name: Package image file
      id: package
      run: |
        # Cari file dengan batasan 1 hasil
        FILE_PATH=$(find output -type f -name "${{ github.event.inputs.output_name }}" | head -n1)
        
        if [ -z "$FILE_PATH" ] || [ ! -f "$FILE_PATH" ]; then
          echo "::error::File ${{ github.event.inputs.output_name }} tidak ditemukan!"
          echo "Daftar file yang tersedia:"
          find output -type f
          exit 1
        fi
        
        OUTPUT_FILE="${{ github.event.inputs.output_name }}_${{ steps.extract_version.outputs.version }}.zip"
        
        # Zip file tanpa path directory
        zip -j "$OUTPUT_FILE" "$FILE_PATH"
        
        echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV
        echo "::notice::Berhasil membuat package: $OUTPUT_FILE"

    - name: Upload ke GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ steps.extract_version.outputs.version }}"
        name: "MIUI ${{ steps.extract_version.outputs.version }}"
        body: "Extracted ${{ github.event.inputs.output_name }}"
        files: |
          ${{ env.OUTPUT_FILE }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}  # Gunakan token default
