name: MIUI Firmware fastboot Extractor v2

on:
  workflow_dispatch:
    inputs:
      download_url:
        description: 'URL file firmware'
        required: true
      output_name:
        description: 'Pilih jenis image'
        type: choice
        required: true
        options:
          - boot.img
          - system.img
          - logo.bin
          - dtbo.img
          - vbmeta.img
          - scatter.txt

jobs:
  extract-firmware:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y unzip zip curl tar

    - name: Extract version from URL
      id: extract_version
      run: |
        URL="${{ github.event.inputs.download_url }}"
        VERSION=$(echo "$URL" | sed -n 's|.*/\(V[^/]*\)/.*|\1|p')
        
        if [ -z "$VERSION" ]; then
          echo "::error::Gagal ekstrak versi dari URL!"
          exit 1
        fi
        
        echo "Extracted version: $VERSION"
        echo "::set-output name=version::${VERSION}"

    - name: Extract codename from URL
      id: extract_codename
      run: |
        URL="${{ github.event.inputs.download_url }}"
        
        CODENAME=$(echo "$URL" | sed -n 's|.*/\(.*\)_global_images.*|\1|p')
        
        if [ -z "$CODENAME" ]; then
          echo "::error::Gagal ekstrak codename dari URL!"
          exit 1
        fi
        echo "Extracted codename: $CODENAME"
        echo "::set-output name=codename::${CODENAME}"

    - name: Download file
      run: |
        curl -L "${{ github.event.inputs.download_url }}" -o input_file.tgz

    - name: Extract files
      run: |
        mkdir -p output
        tar -xvzf input_file.tgz -C output

    - name: Package image file
      run: |
        FILE_PATH=$(find output -type f -name "${{ github.event.inputs.output_name }}" | head -n1)
        OUTPUT_FILE="${{ github.event.inputs.output_name }}_${{ steps.extract_version.outputs.version }}.zip"
        
        if [ ! -f "$FILE_PATH" ]; then
          echo "::error::File $FILE_PATH tidak ditemukan!"
          exit 1
        fi
        
        zip "$OUTPUT_FILE" "$FILE_PATH"
        echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

    - name: Upload ke GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.extract_version.outputs.codename }}
        name: ${{ steps.extract_version.outputs.codename }}
        files: |
          ${{ env.OUTPUT_FILE }}
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
